### ISSUE TITLE
initialize() method occasionally throws PlatformException(MEDIA_ERR_NETWORK, networkError, manifestLoadError, null) 

### ISSUE THREAD

**Issue by NickSereda** [balvinderz/video_player_web_hls#27]
VideoPlayerController.network(url)..initialize() method occasionally(not always) throws PlatformException(MEDIA_ERR_NETWORK, networkError, manifestLoadError, null) for a valid m3u8 urls, tested with other players, seems like they load the same urls successfully.

The problem occurs, when trying to re-initialize controller with different url (when re-initializing controller with same url, it seems to load successfully).

**Comment by NickSereda** [comment]
**Web error logs:** 
PlatformException(MEDIA_ERR_NETWORK, networkError, manifestLoadError, null)
**Android error logs:** 
E/ExoPlayerImplInternal(13896): Playback error
E/ExoPlayerImplInternal(13896):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(13896):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:640)
E/ExoPlayerImplInternal(13896):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:612)
E/ExoPlayerImplInternal(13896):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(13896):       at android.os.Looper.loop(Looper.java:201)
E/ExoPlayerImplInternal(13896):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(13896):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal(13896):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:396)
E/ExoPlayerImplInternal(13896):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(13896):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
E/ExoPlayerImplInternal(13896):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
E/ExoPlayerImplInternal(13896):       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
E/ExoPlayerImplInternal(13896):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(13896):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(13896):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(13896):       at java.lang.Thread.run(Thread.java:764)
[log] PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)

**Comment by NickSereda** [comment]
Closing the issue, seems like the problem persists in other players and is related to the streams that I'm using.
